Repository phasorpy/phasorpy, pull requests merged in 2024-03, with the labels that each got.

#38 Mention code contributions
  README.md
  docs/contributing.rst
Labels: documentation

#36 Add plot module
  docs/api/index.rst
  docs/api/plot.rst
  docs/conf.py
  requirements_dev.txt
  src/phasorpy/_utils.py
  src/phasorpy/plot.py
  tests/test__utils.py
  tests/test_plot.py
  tutorials/phasorpy_introduction.py
  tutorials/phasorpy_phasor_from_lifetime.py
  tutorials/phasorpy_phasorplot.py
Labels: enhancement

#39 Fix PhasorPlot.semicircle changes axes limits
  src/phasorpy/plot.py
  tests/test_plot.py
Labels: bug

#40 Fix contour offsets
  src/phasorpy/plot.py
  tests/test_plot.py
Labels: bug

#37 Higher level calibration function
  src/phasorpy/phasor.py
  src/phasorpy/plot.py
  tests/test_phasor.py
  tutorials/phasorpy_introduction.py
Labels: enhancement

#41 Hide typehints in API documentation
  docs/conf.py
Labels: documentation

#42 Add `skip_axes` to `phasor_calibrate`
  src/phasorpy/phasor.py
Labels: enhancement

#44 Additions and improvements to the phasor module
  .gitignore
  pyproject.toml
  setup.py
  src/phasorpy/_phasor.pyx
  src/phasorpy/phasor.py
  tests/test_phasor.py
Labels: enhancement

#45 Improve typing
  pyproject.toml
  src/phasorpy/_utils.py
  src/phasorpy/phasor.py
  src/phasorpy/plot.py
  tests/test_phasor.py
  tutorials/phasorpy_introduction.py
  tutorials/phasorpy_phasorplot.py
Labels: enhancement

#46 Add dtime parameter to read_ptu function
  src/phasorpy/io.py
  tests/test_io.py
Labels: enhancement
