Repository phasorpy/phasorpy, pull requests merged in 2024-11, with the labels that each got.

#143 Add tool to print SHA256 hashes of dataset files
  tools/sha256.py
Labels: maintenance or infrastructure

#145 Add Convallaria dataset
  src/phasorpy/datasets.py
Labels: enhancement

#146 Mention LIFA software
  docs/phasor_approach.rst
Labels: documentation

#149 Upgrade GitHub Actions to macOS-13 environment
  .github/workflows/build_wheels.yml
  .github/workflows/run-tests.yml
Labels: maintenance or infrastructure

#148 Add spectral vector denoising
  src/phasorpy/_phasorpy.pyx
  src/phasorpy/utils.py
  tests/test_utils.py
Labels: enhancement

#147 Replace median filter implementation for NaN handling consistency
  src/phasorpy/_phasorpy.pyx
  src/phasorpy/phasor.py
  tests/test_nan.py
  tests/test_phasor.py
  tutorials/api/phasorpy_multi-harmonic.py
Labels: enhancement

#150 Improve median filter
  src/phasorpy/_phasorpy.pyx
  src/phasorpy/phasor.py
Labels: enhancement

#151 Release v0.2
  docs/_static/switcher.json
  docs/release.rst
  src/phasorpy/version.py
Labels: maintenance or infrastructure

#152 Bump version
  src/phasorpy/version.py
Labels: maintenance or infrastructure
