Repository phasorpy/phasorpy, pull requests merged in 2024-08, with the labels that each got.

#85 Add median filtering function
  pyproject.toml
  src/phasorpy/phasor.py
  tests/test_phasor.py
  tutorials/phasorpy_introduction.py
Labels: enhancement

#91 Fix type of harmonic parameter in phasor_to_signal
  src/phasorpy/phasor.py
Labels: bug

#63 Add LFD workshop FLIM tutorial
  tutorials/phasorpy_lfd_workshop.py
Labels: documentation

#93 Add lifetime_to_signal function
  src/phasorpy/_phasorpy.pyx
  src/phasorpy/phasor.py
  tests/test_phasor.py
  tutorials/phasorpy_lfd_workshop.py
  tutorials/phasorpy_lifetime_to_signal.py
Labels: enhancement

#94 Use Cython>=3.0.11
  pyproject.toml
  requirements_dev.txt
  src/phasorpy/_phasorpy.pyx
Labels: enhancement

#96 Fix phasor_center with NaN input
  src/phasorpy/phasor.py
  tests/test_phasor.py
Labels: bug

#97 Fix RuntimeWarning in plot_phasor_image
  src/phasorpy/plot.py
  tests/test_plot.py
Labels: bug

#98 Unify phasor_from_signal functions
  src/phasorpy/_phasorpy.pyx
  src/phasorpy/phasor.py
  tests/test_phasor.py
  tutorials/benchmarks/phasorpy_phasor_from_signal.py
Labels: enhancement

#88 Add `phasor_threshold` function to `phasor` module.
  src/phasorpy/_phasorpy.pyx
  src/phasorpy/phasor.py
  tests/test_phasor.py
  tutorials/phasorpy_introduction.py
  tutorials/phasorpy_lfd_workshop.py
Labels: enhancement

#100 Fix undefined and not defined function names in `_utils`.
  src/phasorpy/_utils.py
Labels: bug

#101 Improve handling of NaN values
  src/phasorpy/_phasorpy.pyx
  src/phasorpy/components.py
  src/phasorpy/cursors.py
  src/phasorpy/phasor.py
  tests/test__phasorpy.py
  tests/test_nan.py
  tests/test_plot.py
  tutorials/phasorpy_lfd_workshop.py
Labels: enhancement

#103 Add default fractions to graphical_component_analysis
  src/phasorpy/components.py
  tests/test_components.py
Labels: enhancement

#102 Improve tutorials
  src/phasorpy/components.py
  src/phasorpy/cursors.py
  src/phasorpy/phasor.py
  src/phasorpy/plot.py
  tutorials/README.rst
  tutorials/api/README.rst
  tutorials/api/phasorpy_components.py
  tutorials/api/phasorpy_cursors.py
  tutorials/api/phasorpy_fret.py
  tutorials/api/phasorpy_lifetime_to_signal.py
  tutorials/api/phasorpy_pca.py
  tutorials/api/phasorpy_phasor_from_lifetime.py
  tutorials/api/phasorpy_phasorplot.py
  tutorials/applications/README.rst
  tutorials/benchmarks/README.rst
  tutorials/benchmarks/phasorpy_phasor_from_signal.py
  tutorials/phasorpy_introduction.py
Labels: documentation

#104 Support writing multi-harmonic phasors to OME-TIFF
  docs/conf.py
  pyproject.toml
  src/phasorpy/io.py
  tests/test_io.py
  tests/test_phasor.py
  tutorials/api/README.rst
  tutorials/phasorpy_introduction.py
Labels: enhancement
