Repository phasorpy/phasorpy, pull requests merged in 2024-05, with the labels that each got.

#66 Format docstring examples with blackdoc
  .github/workflows/run-tests.yml
  docs/contributing.rst
  requirements_dev.txt
  src/phasorpy/_utils.py
  src/phasorpy/components.py
  src/phasorpy/phasor.py
Labels: documentation, dependencies

#65 Add phasor_at_harmonic function
  src/phasorpy/_phasorpy.pyx
  src/phasorpy/phasor.py
  tests/conftest.py
  tests/test_phasor.py
Labels: enhancement

#69 Fix `phasor_calibrate` to handle multi harmonic calibration
  src/phasorpy/phasor.py
  tests/test_phasor.py
Labels: bug

#70 Mention FLIMfit software
  docs/phasor_approach.rst
Labels: documentation
