Repository phasorpy/phasorpy, pull requests merged in 2025-02, with the labels that each got.

#185 Bug Fix for `phasor_calibrate` when skipping axes with harmonic axis
  src/phasorpy/phasor.py
  tests/test_phasor.py
Labels: bug

#184 Fixes for liffile 2025.2.6
  pyproject.toml
  requirements_min.txt
  src/phasorpy/_io.py
  tests/test_io.py
Labels: bug

#186 Fix phasor_normalize with numpy 1.24
  src/phasorpy/phasor.py
  tests/test_phasor.py
Labels: bug

#167 Add pawFLIM wavelet filter for phasor coordinates
  pyproject.toml
  requirements_dev.txt
  src/phasorpy/phasor.py
  tests/test_phasor.py
  tutorials/api/phasorpy_filtering.py
Labels: enhancement

#187 Add dataset from zenodo.org/records/14860228
  src/phasorpy/datasets.py
Labels: enhancement

#188 Improve support for Leica image files
  pyproject.toml
  requirements_min.txt
  src/phasorpy/_io.py
  src/phasorpy/datasets.py
  tests/test_io.py
  tutorials/api/phasorpy_io.py
Labels: enhancement

#189 Remove notes about early stage of development
  docs/api/index.rst
  docs/index.rst
  docs/release.rst
Labels: documentation

#191 Add plot_histograms function
  src/phasorpy/plot.py
  tests/test_plot.py
  tutorials/api/phasorpy_components.py
  tutorials/api/phasorpy_io.py
Labels: enhancement

#192 Fix NaN padding in phasor_to_simfcs_referenced
  src/phasorpy/_io.py
  tests/test_io.py
Labels: bug

#193 Return more metadata from IFLI and FBD readers
  src/phasorpy/_io.py
  src/phasorpy/datasets.py
  tests/test_io.py
Labels: enhancement

#194 Add more formats to file I/O tutorial
  src/phasorpy/datasets.py
  tutorials/api/phasorpy_components.py
  tutorials/api/phasorpy_cursors.py
  tutorials/api/phasorpy_io.py
Labels: documentation

#195 Fix module attribute of functions in phasorpy.io
  src/phasorpy/_utils.py
  src/phasorpy/io.py
  tests/test__utils.py
Labels: maintenance or infrastructure

#196 Add plot_image helper function
  src/phasorpy/_utils.py
  src/phasorpy/components.py
  src/phasorpy/datasets.py
  src/phasorpy/plot.py
  src/phasorpy/utils.py
  tests/test_plot.py
  tutorials/api/phasorpy_cursors.py
  tutorials/api/phasorpy_filtering.py
  tutorials/phasorpy_introduction.py
Labels: enhancement
