Repository phasorpy/phasorpy, pull requests merged in 2025-08, with the labels that each got.

#276 Build wheels for free-threaded Python
  .github/workflows/build_wheels.yml
  .github/workflows/run-tests.yml
  pyproject.toml
Labels: maintenance or infrastructure

#279 Rename build_manylinux scripts
  MANIFEST.in
  tools/build_manylinux.cmd
  tools/build_manylinux.sh
Labels: maintenance or infrastructure

#280 Add tutorial to create PhasorPy logo
  .gitignore
  docs/_static/logo.png
  docs/_static/phasorpy_logo.svg
  docs/conf.py
  src/phasorpy/phasor.py
  tutorials/benchmarks/README.rst
  tutorials/misc/README.rst
  tutorials/misc/phasorpy_logo.py
  tutorials/misc/phasorpy_phasor_from_signal.py
Labels: documentation

#281 Make PhasorPy logo square shaped
  docs/_static/phasorpy_logo.png
  docs/_static/phasorpy_logo.svg
  tutorials/misc/phasorpy_logo.py
Labels: documentation

#286 Document that LIF files contain Fast FLIM lifetimes
  src/phasorpy/io/_leica.py
  tutorials/api/phasorpy_io.py
Labels: documentation

#283 Add multidimensional phasor tutorial and dataset
  docs/conf.py
  src/phasorpy/datasets.py
  tutorials/applications/phasorpy_multidimensional.py
Labels: documentation, enhancement

#287 Bump version
  src/phasorpy/__init__.py
Labels: maintenance or infrastructure
